version: '3.8'

volumes:
  pg-data:
  redis-data:

services:
  lamp:
    image: mattrayner/lamp:latest-2004-php8
    volumes:
      - "./www:/app"
    ports:
      - "80:80"
      - "3306:3306"

networks:
  my_app_net: